//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace U8StarterKit.Web.Models.Umbraco
{
	// Mixin Content Type with alias "fontAwesomeComposition"
	/// <summary>Font Awesome Composition</summary>
	public partial interface IFontAwesomeComposition : IPublishedElement
	{
		/// <summary>Font Awesome Class</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		string FontAwesomeClass { get; }

		/// <summary>Font Awesome Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		string FontAwesomeSize { get; }
	}

	/// <summary>Font Awesome Composition</summary>
	[PublishedModel("fontAwesomeComposition")]
	public partial class FontAwesomeComposition : PublishedElementModel, IFontAwesomeComposition
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "fontAwesomeComposition";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FontAwesomeComposition, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public FontAwesomeComposition(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Font Awesome Class: See the font awesome icon class name. Eg. "fas fa-cube"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("fontAwesomeClass")]
		public string FontAwesomeClass => GetFontAwesomeClass(this);

		/// <summary>Static getter for Font Awesome Class</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static string GetFontAwesomeClass(IFontAwesomeComposition that) => that.Value<string>("fontAwesomeClass");

		///<summary>
		/// Font Awesome Size
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("fontAwesomeSize")]
		public string FontAwesomeSize => GetFontAwesomeSize(this);

		/// <summary>Static getter for Font Awesome Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static string GetFontAwesomeSize(IFontAwesomeComposition that) => that.Value<string>("fontAwesomeSize");
	}
}
