//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace U8StarterKit.Web.Models.Umbraco
{
	// Mixin Content Type with alias "fontAwesomeComposition"
	/// <summary>Font Awesome Composition</summary>
	public partial interface IFontAwesomeComposition : IPublishedElement
	{
		/// <summary>Font Awesome Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IEnumerable<FaLinksPropertyEditor.Models.FaLink> FontAwesomeLink { get; }

		/// <summary>Font Awesome Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		decimal FontAwesomeSize { get; }
	}

	/// <summary>Font Awesome Composition</summary>
	[PublishedModel("fontAwesomeComposition")]
	public partial class FontAwesomeComposition : PublishedElementModel, IFontAwesomeComposition
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "fontAwesomeComposition";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FontAwesomeComposition, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public FontAwesomeComposition(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Font Awesome Link: See the font awesome icon class name. Eg. "fas fa-cube"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("fontAwesomeLink")]
		public IEnumerable<FaLinksPropertyEditor.Models.FaLink> FontAwesomeLink => GetFontAwesomeLink(this);

		/// <summary>Static getter for Font Awesome Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IEnumerable<FaLinksPropertyEditor.Models.FaLink> GetFontAwesomeLink(IFontAwesomeComposition that) => that.Value<IEnumerable<FaLinksPropertyEditor.Models.FaLink>>("fontAwesomeLink");

		///<summary>
		/// Font Awesome Size: Choose the size of the panel icon.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("fontAwesomeSize")]
		public decimal FontAwesomeSize => GetFontAwesomeSize(this);

		/// <summary>Static getter for Font Awesome Size</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static decimal GetFontAwesomeSize(IFontAwesomeComposition that) => that.Value<decimal>("fontAwesomeSize");
	}
}
