//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace U8StarterKit.Web.Models.Umbraco
{
	// Mixin Content Type with alias "navigation"
	/// <summary>Navigation</summary>
	public partial interface INavigation : IPublishedContent
	{
		/// <summary>Brand Logo</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> BrandLogo { get; }

		/// <summary>Left Nav</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> LeftNav { get; }

		/// <summary>Right Nav</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> RightNav { get; }

		/// <summary>Utility Links</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> UtilityLinks { get; }
	}

	/// <summary>Navigation</summary>
	[PublishedModel("navigation")]
	public partial class Navigation : PublishedContentModel, INavigation
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "navigation";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Navigation, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Navigation(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Brand Logo: Pick Font Awesome Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("brandLogo")]
		public IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> BrandLogo => GetBrandLogo(this);

		/// <summary>Static getter for Brand Logo</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> GetBrandLogo(INavigation that) => that.Value<IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink>>("brandLogo");

		///<summary>
		/// Left Nav
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("leftNav")]
		public IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> LeftNav => GetLeftNav(this);

		/// <summary>Static getter for Left Nav</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> GetLeftNav(INavigation that) => that.Value<IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink>>("leftNav");

		///<summary>
		/// Right Nav
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("rightNav")]
		public IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> RightNav => GetRightNav(this);

		/// <summary>Static getter for Right Nav</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> GetRightNav(INavigation that) => that.Value<IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink>>("rightNav");

		///<summary>
		/// Utility Links: Add utility links, eg. "sign up", "log in"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("utilityLinks")]
		public IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> UtilityLinks => GetUtilityLinks(this);

		/// <summary>Static getter for Utility Links</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink> GetUtilityLinks(INavigation that) => that.Value<IEnumerable<FaLinksPropertyEditor.PropertyValueConverters.FaLink>>("utilityLinks");
	}
}
